"""Generate the ESP32 CA bundle directly from Google's official PEM files."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import ssl
from urllib.request import urlopen

SOURCES = (
    "https://pki.goog/repo/certs/gtsr4.pem",
    "https://pki.goog/repo/certs/gsr1.pem",
)
TARGET = Path(__file__).resolve().parents[1] / "firmware/include/tls_roots.h"


def certificates() -> list[str]:
    result: list[str] = []
    for url in SOURCES:
        with urlopen(url, timeout=15) as response:
            payload: bytes = response.read(16385)
        if len(payload) > 16384:
            raise ValueError("CA response exceeds the size limit")
        pem = payload.decode("ascii").replace("\r\n", "\n").strip()
        if (
            re.fullmatch(
                r"-----BEGIN CERTIFICATE-----\n[A-Za-z0-9+/=\n]+\n-----END CERTIFICATE-----",
                pem,
            )
            is None
        ):
            raise ValueError("CA response is not a single PEM certificate")
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        context.load_verify_locations(cadata=pem)
        result.append(pem)
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    roots = certificates()
    if options.check:
        stored = re.findall(
            r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----",
            TARGET.read_text(encoding="utf-8"),
            re.S,
        )
        if stored != roots:
            raise ValueError("Firmware CA bundle differs from the official files")
        print("Firmware CA certificates match the official files exactly.")
        return
    comments = "\n".join(
        f"// {url}\n// PEM SHA-256: {hashlib.sha256((pem + chr(10)).encode()).hexdigest()}"
        for url, pem in zip(SOURCES, roots)
    )
    bundle = "\n\n".join(roots) + "\n"
    TARGET.write_text(
        "#pragma once\n\n// Generated by scripts/update-ca.py; do not transcribe PEM by hand.\n"
        + comments
        + "\nnamespace tls_roots {\n"
        + 'constexpr char kOpenCodeTrustAnchors[] = R"PEM('
        + bundle
        + ')PEM";\n}  // namespace tls_roots\n',
        encoding="utf-8",
    )
    print("Firmware CA bundle regenerated from the official files.")


if __name__ == "__main__":
    main()
